stages:
  - build

variables:
  AWS_DEFAULT_REGION: eu-west-1
  DOCKER_TLS_CERTDIR: ""

image: antoinegomez/docker:latest

.build_template: &build_template
  when: manual
  only:
    - master
    - tag
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
    - export DOCKERFILE NAME TAG AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION
    - $(aws ecr get-login --no-include-email)
    - ./build.sh

build_kong:
  <<: *build_template
  variables:
    NAME: kong
    TAG: latest
    DOCKERFILE: kong/Dockerfile

build_php:
  <<: *build_template
  variables:
    NAME: php
    TAG: 7.3-fpm
    DOCKERFILE: php/7.3/Dockerfile

build_ecs:
  <<: *build_template
  variables:
    NAME: ecs-updater
    TAG: latest
    DOCKERFILE: nodejs/ecs/Dockerfile

build_nodejs_build:
  <<: *build_template
  variables:
    NAME: node
    TAG: 12.16.1-alpine-build
    DOCKERFILE: nodejs/alpine-build/Dockerfile
