FROM node:10.16.3-alpine
MAINTAINER Antoine Gomez <antoine@gomez.lu>

RUN apk update && apk upgrade && \
apk add --no-cache build-base automake autoconf bash git openssh python mysql-client redis libpng-dev libjpeg-turbo-dev rsync unzip tar p7zip libwebp libwebp-tools pngquant optipng gifsicle
